environment         = "prod"
aws_region          = "us-east-1"
vpc_cidr            = "10.0.0.0/16"
availability_zones  = ["us-east-1a", "us-east-1b"]
instance_type       = "2048"
db_instance_class   = "db.t3.medium"
db_multi_az         = true
db_name             = "dataquest_prod"
db_username         = "admin"
db_password         = "ChangeMeProd123!"
